### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [mizunotlt/tableFun#1]
1. У Вашего класса нет конструктора по умолчанию (без аргументов), который создавал бы функцию с пустой таблицей.
1. Конструктор из `HashMap`. Во-первых, лучше чтобы он принимал просто `Map`. Во-вторых, нужно скопировать содержимое передаваемого `Map`, а не только ссылку на него.
1. Множество всех пар нужно возвращать именно как пары, а не как строки. И лучше, если метод будет возвращать что-нибудь более абстрактное, чем `ArrayList`.
1. Метод `findXY` тоже должен возвращать пару в виде пары, а не в виде строки.
1. Вы неправильно перебираете элементы в методах `findXY` и `interpolXY`. Во-первых, `values` возвращает коллекцию значений, а не ключей (то есть `y`), а значит Вам очень повезёт, если Вы сможете что-нибудь получить (`get`) по такому ключу. Во-вторых, в `min` Вы записываете саму очередную координату, а сравниваете с расстоянием до переданного аргумента.
1. По-моему, формула для интерполяции у Вас неверна.
1. В Вашей задаче целесообразнее использовать `TreeMap` вместо `HashMap`, тогда последние два метода заметно упростятся.
1. У Вас нет тестов.

**Comment by mizunotlt** [comment]
исправил

**Comment by maximpetrov** [comment]
1. `findXY` должна возвращать ближайшую точку, а не ближайшую меньшую. То есть Вам нужно взять ближайшую меньшую, ближайшую большую и вернуть ту, которая ближе к заданной. Кроме того, можно использовать не `floorKey`, а `floorEntry`, чтобы получить сразу пару `(x, y)`, а не искать `y` ещё раз по ключу.
1. `interpolXY`не должна пытаться интерполировать за крайними точками (хотя бы потому, что это уже не интерполяция, а экстраполяция). Так что если одна из границ `null`, то нужно просто вернуть `null`. Кроме того тоже замечание про `floorKey` -> `floorEntry`.
1. Вы забыли добавить возвращаемое значение в `removeXY`.

**Comment by mizunotlt** [comment]
поправил

**Comment by maximpetrov** [comment]
1. Вы меня явно недопоняли про `floorKey` -> `floorEntry`. Я хочу, чтобы Вы заменили именно `floorKey`, а не `get`. То есть вместо получения ближайшего ключа, получайте сразу пару ближайший ключ + его значение, а потом просто используйте поля этой пары.
1. Мы с Вами вроде договаривались, что `removeXY` должна возвращать `boolean`, который будет означать, была удалена точка или нет.

**Comment by mizunotlt** [comment]
Вот так , или я снова не так понял ?

**Comment by maximpetrov** [comment]
1. Да, все правильно, только уберите неиспользуемый `right` из `findXY`.
1. В `removeXY` для определения была точка удалена или нет, лучше использовать возвращаемое значение `remove`.

**Comment by mizunotlt** [comment]
сделал
